[webservers]
  web-1 ansible_host=10.0.1.3 fqdn=fhmspqb4h29n7ofcr8p9.auto.internal
  web-2 ansible_host=10.0.1.7 fqdn=fhm1cs8eot5d65svp3mg.auto.internal

  [databases]
  main ansible_host=10.0.1.12 fqdn=fhm7bkv4f84tvhibt2f6.auto.internal
  replica ansible_host=10.0.1.14 fqdn=fhm5r6g556deqc54t2c3.auto.internal

  [storage]
  storage ansible_host=10.0.1.15 fqdn=fhmf54gchaimssv26tr8.auto.internal

